### ISSUE TITLE
ImportError: No module named Image

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manpaz/python-escpos#15]
```
I'm getting an import error after following the instructions for the Raspberry 
Pi.  It's a fresh install of the latest Raspbian image, and I'm using an Epson 
TM-T20 over USB.  I installed the dependencies as per the instructions, and 
obtained the vendor and product ID.

This is my test code:

from escpos import *
Epson = printer.Usb(0x04b8,0x0e03)
Epson.text("Hello World\n")
Epson.cut()

This is the error message:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from escpos import *
  File "/usr/local/lib/python2.7/dist-packages/escpos/escpos.py", line 9, in <module>
    import Image
ImportError: No module named Image

Can anyone help?
```

Original issue reported on code.google.com by `jx2DITIv...@googlemail.com` on 11 Oct 2013 at 5:15

**Comment by manpaz** [comment]
Image has been renamed to PIL, the proper changes have been committed.
Also, instructions to install QR and some other dependencies are available at https://github.com/manpaz/python-escpos/wiki/Dependencies

Thank you!
